### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Njord201** [6im0n/Arcade#10]
# :white_check_mark: What's needed
Make the Snake game according to these different criteria:
- [x] The game area is a finite amount of cells. The edges of the area either cannot be passed through or are cyclical.
- [x] The snake starts with a size of 4 cells in the middle of the area.
- [x] The snake moves forward automatically at a constant speed. Each section of its tail follows the exact same path as the head.
- [x] The snake can turn right or left when the corresponding key is pressed.
- [x] The goal of the game is to feed the snake so that it can grow. The game area MUST NEVER have less than one element of food.
- [x] A food element fills a single cell.
- [x] When the head of the snake goes over a cell with food, the food disappears and a one-cell-long section is added at the tail of the snake. The new section appears in the first free tile next to the last cell of the tail. If there is no free cell, the game is over. If a new section is added, a new food element appears.
- [x] When the head of the snake runs into the border of the screen or a part of its body, the game is over

## 📋 Subtasks
- [x] #11 
- [x] #12 
- [x] #13 
- [x] #25 
- [x] #27 
- [x] #30 
- [x] #31 
- [x] #32 
- [x] #34 
- [x] #36 
- [x] #37 
- [x] #42 
- [x] #43
