### ISSUE TITLE
Create Snake element

### ISSUE THREAD

**Issue by Njord201** [6im0n/Arcade#12]
# :white_check_mark: What's needed
Create the Snake element, it must be able to move by following its body. It can also move left or right depending on the keys pressed.

## 📋 Subtasks
- [x] Create the snake element (4 part at start of the game)
- [x] Make the Snake moving
- [x] Make the Snake turn (left or right)
