### ISSUE TITLE
Graphics libraries

### ISSUE THREAD

**Issue by 6im0n** [6im0n/Arcade#21]
# :white_check_mark: What's needed
Chose and make the implementation of the lib for the arcade.

## 📋 Subtasks

- [x] SDL2 Implementation  [Documentation](https://wiki.libsdl.org/SDL2/FrontPage)
- [x] SFML Implemantation [Documentation](https://www.sfml-dev.org/learn.php)
- [x] Ncurse Implemantation [Docuementation](https://arnaud-feltz.developpez.com/tutoriels/ncurses/?page=premier_pas)

## :file_folder: Files required
- lib files
