### ISSUE TITLE
Makefile Fixing compilation

### ISSUE THREAD

**Issue by 6im0n** [6im0n/Arcade#65]
# :white_check_mark: What's needed
Makefile compilation fixing

## 📋 Subtasks
- [ ] Fix the compilation of the makefile use classes rules to compile only classes
- [ ] remove classes of the game (snake and core) to compile only one time needed for all rules
- [ ] refactor the cflags lines
- [ ] typo error in the SFML_FLAGS

## :file_folder: Files required
Makefile
