### ISSUE TITLE
Create Centipede game

### ISSUE THREAD

**Issue by Njord201** [6im0n/Arcade#78]
# :white_check_mark: What's needed
To create the centipede game, it must meet these criteria:
- [x] The game area is split in two: a walkable area and a non-walkable area. The walkable area is at the bottom of the screen. It fills the entire width of the screen but only 20% of its height.
- [x] Centipedes come from the top of the screen. They move from side to side and encountering an obstacle or screen border makes them move down a line. A centipede is a snake composed of several parts.
- [x] The player can shoot. When a shot hits a centipede, it is split in half. The part that was hit turns into an obstacle, the head part keeps moving on and the tail part collides with the obstacle, moving down a line and turning back.
- [x] If a centipede touches the player, they lose the game.
- [x] If a centipede touches the bottom of the screen, the player loses score.
- [x] The player wins if they survive 20 centipedes. The map is then reset and the game starts over.
- [x] A Centipede map contains randomly generated obstacles.
- [x] An obstacle can be destroyed by shooting it 5 times.
- [x] There can only be one shot on the screen at any given time

## 📋 Subtasks

- [x] #79 
- [x] #80
