### ISSUE TITLE
Create the Snake for Centipede game

### ISSUE THREAD

**Issue by Njord201** [6im0n/Arcade#80]
# :white_check_mark: What's needed
Create the Snake entities, compose of fiew SnakeBody, with the methods.

## 📋 Subtasks
- [ ] Create move methods
- [ ] Create killSnake method
- [ ] Create removeSnake method
